name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # @weekly

jobs:
  main:
    name: Main
    runs-on: ubuntu-18.04
    env:
      GOPATH: "${{ github.workspace }}/go:/usr/share/gocode"
      GOBIN: "${{ github.workspace }}/go/bin"
      LD_LIBRARY_PATH: "${{ github.workspace }}/go/src/github.com/libgit2/git2go/dynamic-build/install/lib/"
      PKG_CONFIG_PATH: "${{ github.workspace }}/go/src/github.com/libgit2/git2go/dynamic-build/build/"
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/jmahler/rgm
    - name: Checkout Go Packages
      run: |
        go get -d github.com/libgit2/git2go
        go get -d github.com/pborman/getopt/v2
        go get -d golang.org/x/crypto/openpgp
    - name: Install Packages
      run: |
        sudo apt install cmake libssh2-1-dev libssl-dev zlib1g-dev libpcre3-dev
    - name: Setup git2go (dynamic)
      working-directory: "${{ github.workspace }}/go/src/github.com/libgit2/git2go"
      run: |
        git checkout master
        git submodule update --init
        make test-dynamic
        make install-dynamic
    - name: Build
      run: |
        go build github.com/jmahler/rgm github.com/jmahler/rgm/rgm
    - name: Run go fmt
      working-directory: "${{ github.workspace }}/go/src/github.com/jmahler/rgm"
      run: |
        DIFF="$(gofmt -d -s .)"
        test -z "${DIFF}" || (echo "${DIFF}" && exit 1)
    - name: Install CLI
      run: |
        go install github.com/jmahler/rgm/rgm
        echo "${GOBIN}" >> $GITHUB_PATH
    - name: Test
      run: |
        go test -coverprofile=profile.cov github.com/jmahler/rgm
        # test the cli but leave out coverage since it isn't useful
        go test github.com/jmahler/rgm/rgm
    - name: Integration Tests
      run: |
        go test -tags=integration github.com/jmahler/rgm
        go test -tags=integration github.com/jmahler/rgm/rgm
    - name: Send Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
